M48
; DRILL file {KiCad 7.0.9} date Sat Jan 13 15:58:05 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-13T15:58:05+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X128.0Y-49.0
X128.0Y-124.0
X235.0Y-49.0
X235.0Y-124.0
T2
X213.457Y-108.966
T0
M30
